source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.3squared.com:iOSLibraries/CocoaPodSpecs.git'

target 'Meadow Example iOS' do

	platform :ios, '11.3'

	inherit! :search_paths

	pod 'Meadow', :path => '../'
	pod 'Pasture', :path => '../../Pasture'

end

target 'Meadow Example macOS' do

	platform :osx, '10.13'

	inherit! :search_paths

	pod 'Meadow', :path => '../'
	pod 'Pasture', :path => '../../Pasture'

end
