//
//  Grid.swift
//  Meadow
//
//  Created by Zack Brown on 26/04/2018.
//  Copyright © 2018 Script Orchard. All rights reserved.
//

import SceneKit

/*!
 @protocol GridDelegate
 @abstract Delegate resolution of dirty nodes to an external handler.
 @discussion As a means to update the grid in which the node is contained, resolution of dirty nodes must be passed upwards to inform the delegate of any changes.
 */
public protocol GridDelegate {
    
    func didBecomeDirty(node: GridNode)
}

/*!
 @class Grid
 @abstract Grid is the top level parent class for all grid chunk, tiles and nodes.
 @discussion The grid provides the basic means to add and remove nodes with specified bounding volumes. Child chunks will be cleaned and any geometry generated by any attached nodes. This provides a bear bones implementation and any additional functionality should be added by subclassing.
 */
public class Grid<Chunk: GridChunk<Tile, Node>, Tile: GridTile<Node>, Node: GridNode>: SCNNode {
    
    /*!
     @property delegate
     @abstract Delegate to inform when grid nodes become dirty.
     */
    private let delegate: GridDelegate
    
    /*!
     @property isDirty
     @abstract Represents staleness of the grid.
     */
    private var isDirty: Bool = false
    
    /*!
     @method init:delegate
     @abstract Creates and initialises a grid with the specified delegate.
     @param delegate The delegate to call out to when grid becomes dirty.
     */
    public required init(delegate: GridDelegate) {
        
        self.delegate = delegate
        
        super.init()
    }
    
    /*!
     @method initWithCoder
     @abstract Support coding and decoding via NSKeyedArchiver.
     */
    public required init?(coder aDecoder: NSCoder) {
        
        fatalError("init(coder:) has not been implemented")
    }
}

extension Grid: GridDelegate {
    
    /*!
     @method didBecomeDirty:node
     @abstract GridDelegate callback to delegate grid node resultion upwards.
     @discussion As a means to update the grid in which the node is contained, resolution of dirty nodes must be passed upwards to inform the delegate of any changes.
     */
    public func didBecomeDirty(node: GridNode) {
        
        delegate.didBecomeDirty(node: node)
    }
}

extension Grid {
    
    /*!
     @method becomeDirty
     @abstract If not already true, toggle the isDirty flag to true.
     */
    func becomeDirty() {
        
        if isDirty { return }
        
        isDirty = true
    }
    
    /*!
     @method clean
     @abstract Enumerate through children and clean each chunk.
     */
    func clean() {
        
        if !isDirty { return }
            
        chunks.forEach { chunk in
            
            chunk.clean()
        }
        
        isDirty = false
    }
}

extension Grid {
    
    /*!
     @property chunks
     @abstract Cast and return child nodes to array of Chunks.
     */
    private var chunks: [Chunk] {
        
        return childNodes as! [Chunk]
    }
    
    /*!
     @method add:node
     @abstract Attempt to create and return a new grid node with the requested volume.
     @param volume The volume the grid node should occupy
     */
    func add(node volume: Volume) -> Node? {
        
        if let _ = find(node: volume.coordinate) {
        
            return nil
        }
        
        let chunk = find(chunk: volume.coordinate) ?? Chunk(volume: Chunk.FixedVolume(volume.coordinate))
        
        let tile = find(tile: volume.coordinate) ?? Tile(volume: Tile.FixedVolume(volume.coordinate))
        
        let node = Node(delegate: self, volume: volume)
        
        if chunk.parent == nil {
            
            addChildNode(chunk)
        }
        
        chunk.add(tile: tile)
        
        tile.add(node: node)
        
        node.becomeDirty()
        
        return node
    }
    
    /*!
     @method remove:chunk
     @abstract Attempt to find and remove the appropriate chunk at the specified coordinate.
     @param coordinate: Coordinate of the chunk to be found and removed.
     @discussion The coordinate provided will be used to find the nearest enclosing bounds along the x and z axis irrelevant of the y axis value.
     */
    func remove(chunk coordinate: Coordinate) -> Bool {
        
        if let chunk = find(chunk: coordinate) {
            
            chunk.removeFromParentNode()
            
            becomeDirty()
            
            return true
        }
        
        return false
    }
    
    /*!
     @method remove:tile
     @abstract Attempt to find and remove the appropriate tile at the specified coordinate
     @param coordinate: Coordinate of the tile to be found and removed.
     @discussion The coordinate provided will be used to find the tile matching both the x and z axis irrelevant of the y axis value.
     */
    func remove(tile coordinate: Coordinate) -> Bool {
        
        if let chunk = find(chunk: coordinate), let tile = chunk.find(tile: coordinate) {
            
            chunk.remove(tile: tile)
            
            if chunk.isEmpty {
                
                chunk.removeFromParentNode()
            }
            
            becomeDirty()
            
            return true
        }
        
        return false
    }
    
    /*!
     @method remove:node
     @abstract Attempt to find and remove the appropriate node at the specified coordinate
     @param coordinate: Coordinate of the node to be found and removed.
     @discussion The coordinate provided will be used to find the nearest enclosing bounds matching both the x and z axis where the y axis value also intersects with the nodes bounds.
     */
    func remove(node coordinate: Coordinate) -> Bool {
        
        if let chunk = find(chunk: coordinate), let tile = chunk.find(tile: coordinate), let node = tile.find(node: coordinate) {
            
            tile.remove(node: node)
            
            if tile.isEmpty {
                
                chunk.remove(tile: tile)
                
                if chunk.isEmpty {
                    
                    chunk.removeFromParentNode()
                }
            }
            
            chunk.becomeDirty()
            
            becomeDirty()
            
            return true
        }
        
        return false
    }
    
    /*!
     @method find:chunk
     @abstract Attempt to find and return the appropriate chunk at the specified coordinate.
     @param coordinate: Coordinate of the chunk to be found and returned.
     @discussion The coordinate provided will be used to find the nearest enclosing bounds along the x and z axis irrelevant of the y axis value.
     */
    func find(chunk coordinate: Coordinate) -> Chunk? {
     
        return chunks.first { chunk -> Bool in
            
            return chunk.volume.contains(coordinate: coordinate)
        }
    }
    
    /*!
     @method find:tile
     @abstract Attempt to find and return the appropriate tile at the specified coordinate
     @param coordinate: Coordinate of the tile to be found and returned.
     @discussion The coordinate provided will be used to find the tile matching both the x and z axis irrelevant of the y axis value.
     */
    func find(tile coordinate: Coordinate) -> Tile? {
        
        if let chunk = find(chunk: coordinate), let tile = chunk.find(tile: coordinate) {
            
            return tile
        }
        
        return nil
    }
    
    /*!
     @method find:node
     @abstract Attempt to find and return the appropriate node at the specified coordinate
     @param coordinate: Coordinate of the node to be found and returned.
     @discussion The coordinate provided will be used to find the nearest enclosing bounds matching both the x and z axis where the y axis value also intersects with the nodes bounds.
     */
    func find(node coordinate: Coordinate) -> Node? {
        
        if let tile = find(tile: coordinate), let node = tile.find(node: coordinate) {
            
            return node
        }
        
        return nil
    }
}
